version: "3.7"
services:
  mongo:
    image: mongo
    container_name: "mongodb_event"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event
      MONGO_INITDB_ROOT_USERNAME: event
      MONGO_INITDB_ROOT_PASSWORD: password123